### ISSUE TITLE
about the generalization ability of the model

### ISSUE THREAD

**Issue by xkyi1111** [leofansq/CBR#3]
Great work! However, I have some questions and would like to ask if the proposed method has certain generalization ability？ If I use a different intersection dataset, will the proposed method not work anymore?

**Comment by leofansq** [comment]
Theoretically, the calibration-free method is to learn to model the cameras' postures. As a data-driven approach, the generalization ability is depend on the data distribution. As for our method, the experimental results on real-world dataset demonstrate the capability. However, it may not work on a totally different scene if it have not ever taken a look.

**Comment by leofansq** [comment]
For a different intersection dataset, you may need to finetune with your own data.

**Comment by xkyi1111** [comment]
Got it! Thank you for your patient answers.
