### ISSUE TITLE
About the coordinate system of the label

### ISSUE THREAD

**Issue by kowloontong** [leofansq/CBR#4]
Firstly, thanks for your great work.
Secondly, i'm a little confused about the coordinate system of training labels, According to the kitti-format conversion code, I found that the converted label is under the camera coordinate system. (https://github.com/AIR-THU/DAIR-V2X/blob/main/tools/dataset_converter/dair2kitti.py#L76) 
Am i missing any details? if the label is indeed in the camera coordinate system, dose it mean that Calibration-free is only for camera intrinsics?

**Comment by leofansq** [comment]
Different from the monocular 3D detection in vehicle-view scenes, the optical axis of infrastructure-side camera is not parallel to the ground plane due to the pitch angle. Therefore, the method needs to model the pitch angles and mounting height to achieve infrastructure-side perception.

**Comment by kowloontong** [comment]
> 

Thanks for your reply, i understand what you mean.
